config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts
  get 'u/:id' => 'public#profile', as: :profile

  resources :communities do
    resources :posts do
      member do
        put 'upvote', to: 'posts#upvote'
        put 'downvote', to: 'posts#downvote'
      end
    end
    resources :subscriptions
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'public#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :account
  belongs_to :community

  validates_presence_of :title, :body, :account_id, :community_id
  validates_associated :account, :community

  acts_as_votable
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  rescue_from StandardError, with: :catch_no_method
  before_action :authenticate_account!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
    @community = Community.find(params[:community_id])
  end

  def show; end

  def edit; end

  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def create
    @community = Community.find(params[:community_id])
    @post = Post.new post_values
    @post.community_id = params[:community_id]
    @post.account_id = current_account.id
    if member?
      if @post.save
        flash.notice = 'Post created!'
        redirect_to community_path(id: @post.community_id)
      else
        flash.alert = 'Post not created'
        render :new
      end
    else
      flash.alert = 'Must be a member to post'
      render :index
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_values)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to community_posts_url(@post.community_id), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_account
    redirect_to community_post_path(@post)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_account
    redirect_to community_post_path(@post)
  end

  # def trending(int)
  #   communities = Hash.new(0)
  #   @posts.each { |post| communities[post.community_id] += 1 }
  #   sorted_communities = communities.sort_by {|k,v| v}.reverse
  #   id = sorted_communities[int][0]
  #   community = Community.find_by(id: id)
  # end

  private

  def member?
    @community.subscriptions.each do |sub|
      sub.account_id == current_account.id
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_values
    params.require(:post).permit(:title, :body, :account_id, :community_id)
  end

  def catch_not_found(err)
    Rails.logger.debug('There was a not found exception in posts_controller.')
    flash.alert = err.to_s
    redirect_to community_posts_url
  end

  def catch_no_method(err)
    Rails.logger.debug("There was a 'NoMethodError' in posts_controller: #{err} (the object may have been created without all it's attributes.)")
    flash.alert = err.to_s
    redirect_to community_posts_url
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<div class='row'>
	<div class='col-sm-6'>

		<%= form_for [@community, @post] do |f| %>

			<div class='form-group text-danger col-4 new-post'>
				<%= label_tag :title %>
				<%= f.text_field :title, class: 'form-control' %>
			</div>

			<div class='form-group text-danger col-6 new-post'>
				<%= label_tag :body %>
				<%= f.text_area :body, class: 'form-control' %>
			</div>

			<div class='col-2 new-post'>
				<%= f.submit 'Submit', class:'btn btn-danger form-control mt-1' %>
			</div>

		<% end %>

	<%= link_to 'Back', :back, class:'btn btn-danger mt-2 col-3 new-post' %>

	</div>
</div>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
    <div>
        <h4><%= link_to post.title, community_post_path(post.community.id, post.id), class:'text-danger text-decoration-none' %></h4>
        <p><%= truncate post.body, length: 200 %></p>
        <small>
                <p class='text-dark shadow-sm p-2'>Posted in <%= link_to post.community.name.to_s, community_path(post.community.id), class:'text-danger text-decoration-none' %> by <strong><%= link_to post.account.first_name.to_s, profile_path(post.account.id), class:'text-danger text-decoration-none' %> </strong> on <%= post.created_at.strftime('%B %e, %Y')%>
        </small>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class='p-1'>
    <h2 class='text-danger'>Edit Post</h2>

    <%= render partial: 'form', locals: { community: @community, post: @post } %>
</div>

app/views/posts/index.html.erb
<div class='p-1'>
	<h2 class='text-light mb-3'>All Community Posts</h2>
	<%= @posts.each do |post| %>
		<% if post.community_id == @community.id %>
			<div class='row card bg-dark border border-secondary p-2'>
				<h4 class='text-danger'><%= post.title %></h4>
				<p class='text-light'><%= post.body %></p>
				<small>
					<p class='text-light shadow-sm p-2'>Author: <strong><%= link_to post.account.first_name.to_s, profile_path(post.account.id), class:'text-danger text-decoration-none' %> </strong> on <%= post.created_at.strftime('%B %e, %Y')%>
				</small>
			</div>
		<% end %>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class='p-1'>
    <h2 class='text-danger'>New Post</h2>

    <%= render partial: 'form' %>
</div>

app/views/posts/show.html.erb
<div class='p-1'>
	<h2 class='text-light'><%= @post.title %></h2>

	<%= simple_format @post.body, class:'text-danger' %>

	<% if current_account %>
		<% if current_account.communities.include?(@post.community) %>
			<div class='row'>
				<% if current_account.voted_up_on?(@post) %>
					<div class='col-2 float-left text-light mb-1 pt-1 vote-divs'>
						Upvotes: <%= @post.get_upvotes.size %>
					</div>
				<% else %>
					<div class='col-2 float-left text-danger mb-1 vote-divs'>
						<%= link_to upvote_community_post_path(@post.community_id, @post.id), action: :update, method: :put, class: 'btn btn-success' do %>
							<span class="glyphicon glyphicon-chevron-up">
								Upvote
							</span>
						<% end %>
					</div>
				<% end %>
				<% if current_account.voted_down_on?(@post) %>
					<div class='col-2 float-right text-light mb-1 pt-1 vote-divs'>
						Downvotes: <%= @post.get_downvotes.size %>
					</div>
				<% else %>
					<div class='col-2 float-right text-danger mb-1 vote-divs'>
						<%= link_to downvote_community_post_path(@post.community_id, @post.id), action: :update, method: :put, class: 'btn btn-danger' do %>
							<span class="glyphicon glyphicon-chevron-down">
								Downvote
							</span>
						<% end %>
					</div>
				<% end %>
			</div>
		<% end %>

		<% if current_account.posts.include?(@post) %>
			<div class='col-sm-3 mt-4'>
				<%= link_to 'Back', communities_path, class: 'btn btn-secondary' %>
				<%= link_to 'Edit', edit_community_post_path(@post.community_id, @post.id), class: 'btn btn-danger' %>
			</div>
		<% else %>
			<div class='col-sm-3 mt-4'>
				<%= link_to 'Back', communities_path, class: 'btn btn-secondary' %>
			</div>
		<% end %>
	<% end %>
</div>