config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts
  get 'u/:id' => 'public#profile', as: :profile

  resources :communities do
    resources :posts do
      member do
        put 'upvote', to: 'posts#upvote'
        put 'downvote', to: 'posts#downvote'
      end
    end
    resources :subscriptions
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'public#index'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name, :bio, :email, :username
  validates :email, format: { with: /\A\S+@\S+[.]\S+\z/,
                              message: 'Invalid Email' }

  has_many :posts
  has_many :subscriptions
  has_many :communities, through: :subscriptions

  acts_as_voter

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/community.rb
# frozen_string_literal: true

class Community < ApplicationRecord
  belongs_to :account
  has_many :posts
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :account
  # validates :subscribers, uniqueness: { scope: :account_id, case_sensitive: false }

  validates_presence_of :url, :name, :rules, :summary
  validates_associated :account

  def subscriber_count
    Subscription.count
  end
end

app/controllers/communities_controller.rb
# frozen_string_literal: true

class CommunitiesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  rescue_from StandardError, with: :catch_no_method
  before_action :authenticate_account!, except: %i[index show]
  before_action :set_community, except: %i[index create new]

  def index
    @communities = Community.all
  end

  def show
    @posts = @community.posts
    @subscriber_count = @community.subscribers.count
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_values)
    @community.account_id = current_account.id
    if @community.save
      flash.notice = 'Community created successfully'
      redirect_to community_path(id: @community.id)
    else
      flash.alert = 'Something went wrong, community not created'
      render :new
    end
  end

  def update
    respond_to do |format|
      if @community.update(community_values)
        flash.notice = 'Community successfully updated'
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        flash.alert = 'Something went wrong'
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def destroy
    @community.destroy
    respond_to do |format|
      flash.notice = 'Community destroyed'
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_values
    params.require(:community).permit(:name, :summary, :account_id, :url, :rules)
  end

  def catch_not_found(err)
    Rails.logger.debug('There was a not found exception in communities_controller.')
    flash.alert = err.to_s
    redirect_to communities_url
  end

  def catch_no_method(err)
    Rails.logger.debug("There was a 'NoMethodError' in communities_controller: #{err} (the object may have been created without all it's attributes.)")
    flash.alert = err.to_s
    redirect_to communities_url
  end
end

app/helpers/communities_helper.rb
# frozen_string_literal: true

module CommunitiesHelper
end

app/views/communities/_community_options.html.erb
<% community_ids = [] %>
<% if current_account %>
    <% current_account.subscriptions.each { |sub| community_ids << sub.community_id } %>
    <% if community_ids.include?(@community.id) %>
        <% subscription = current_account.subscriptions.find_by(community_id: @community.id) %>
        <%= link_to 'New Community Post', new_community_post_path(@community), class: 'row btn btn-light text-dark mb-1' %>
        <%= link_to 'Leave Community', community_subscription_path(id: subscription.id, community_id: @community.id, account_id: current_account.id), action: :destroy, :method => :delete, class: 'row btn btn-dark text-light' %>
    <% else %>
        <%= link_to 'Join Community', community_subscriptions_path(account_id: current_account.id, community_id: @community.id), action: :create, :method => :post, class: 'row btn btn-success text-light' %>
    <% end %>
    <% if @community.account_id === current_account.id %>
        <%= link_to 'Edit this community', edit_community_path(@community.id), action: :edit, method: :get, class: 'row btn btn-secondary text-light mt-1' %>
        <%= link_to 'Delete this community', community_path(@community.id), action: :destroy, method: :delete, class: 'row btn btn-danger text-light mt-1'%>
    <% end %>
<% end %>

app/views/communities/_form.html.erb
<div class='row p-1'>
	<div class='col-sm-6'>

		<%= form_for @community do |f| %>

			<div class='form-group text-danger'>
				<%= label_tag :name %>
				<%= f.text_field :name, class: 'form-control' %>
			</div>

			<div class='form-group text-danger'>
				<%= label_tag :summary %>
				<%= f.text_field :summary, class: 'form-control' %>
			</div>

			<div class='form-group text-danger'>
				<%= label_tag :url %>
				<%= f.text_field :url, class: 'form-control' %>
			</div>

			<div class='form-group text-danger'>
				<%= label_tag :rules %>
				<%= f.text_area :rules, class: 'form-control' %>
			</div>

			<%= f.submit 'Submit', class:'btn btn-danger mt-2' %>

		<% end %>

	</div>
</div>

app/views/communities/_list.html.erb
<% if communities %>
    <% communities.each do |comm| %>
        <ul class="list-group list-group-flush bg-secondary">
            <li class="list-group-item"><%= link_to comm.name, community_path(id: comm.id), class:'text-danger text-decoration-none' %></li>
        </ul>
    <% end %>
<% elsif !@communities.nil? && communities.nil? %>
    <% @communities.each do |comm| %>
        <ul class="list-group list-group-flush bg-secondary">
            <li class="list-group-item"><%= link_to comm.name, community_path(id: comm.id), class:'text-danger text-decoration-none' %></li>
        </ul>
    <% end %>
<% else %>
    <p>No Communities</p>
<% end %>

app/views/communities/edit.html.erb
<div class='container'>

    <h2 class='text-danger'>New community</h2>

    <%= render partial: 'form' %>

</div>

app/views/communities/index.html.erb
<div class='p-1'>
	<div class='row'>
		<div class='col-sm-9'>
			<% if @communities.size > 0 %>
				<% @communities.each do |community| %>

					<div class='card p-3 bg-light'>
						<h3><%= link_to community.name, community_path(id: community.id), class:'text-danger text-decoration-none' %></h3>
						<%= simple_format community.rules %>
					</div>

				<% end %>
			<% else %>
				<p>No Communities</p>
			<% end %>
		</div>
		
		<% if account_signed_in? %>

			<div class='float-end col-sm-3 p-2'>
				<%= link_to 'New Community', new_community_path, class:'btn btn-outline-danger btn-light text-danger' %>
				<%= link_to 'Home', root_path, class: 'btn btn-outline-light btn-danger text-light' %>
			</div>
		<% else %>
			<div class='col-sm-3 p-2'>
				<%= link_to 'Home', root_path, class: 'btn btn-outline-danger btn-light text-danger' %>
			</div>
		<% end %>
	</div>
</div>

app/views/communities/show.html.erb
<div class='row p-1' id='community-page-div'>
	<h2 class='text-danger'><%= @community.name %></h2>

	<div class='col-8' id='community-list'>
		<% if @community.posts.nil? %>
			<p class='text-danger'>No posts yet</p>
		<% else %>
			<div class='card p-3'>
				<% @posts.each do |post| %>
					<h4><%= link_to post.title, community_post_path(@community, post), class:'text-dark text-decoration-none' %></h4>
					<p class='text-dark float-right'><%= truncate post.body, length: 200 %></p>
					<small class='text-danger mb-1'>Posted by <%= post.account.first_name %> on <%= post.created_at.strftime('%B %d, %Y')%></small>
				<% end %>
			</div>
		<% end %>
	</div>
		
	<div class='col-4 float-end' id='community-options'>
		<div class='card m-2 mt-0 p-3'>
			<p class='h5'>About this community</p>
			<p class='row'><%= simple_format @community.summary %></p>
			<p class='row'><%= simple_format pluralize @subscriber_count, 'member' %></p>
			<p class='small'>Admin: <%= link_to @community.account.full_name, profile_path(@community.account_id), class:'text-danger text-decoration-none' %></p>
			<em class='row text-danger'><strong>Community rules:</strong><%= simple_format @community.rules %></em>
			<%= render partial: 'community_options' %>
		</div>
	</div>
</div>