config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts
  get 'u/:id' => 'public#profile', as: :profile

  resources :communities do
    resources :posts do
      member do
        put 'upvote', to: 'posts#upvote'
        put 'downvote', to: 'posts#downvote'
      end
    end
    resources :subscriptions
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'public#index'
end

app/views/layouts/_footer.html.erb
<div class='row bg-danger'>
</div>

app/views/layouts/_header.html.erb
<div class='container bg-dark navbar-default navbar-expand-lg sticky-top'>
	<div class='row'>
		<div class='col-12 content-divs'>
			<% if account_signed_in? %>
				<div class="dropdown float-end mt-1 shadow-sm">
					<a class="btn btn-danger dropdown-toggle p-2 m-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
						<%= current_account.full_name %>
					</a>

					<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
						<%= button_to 'Profile', profile_path(current_account.id), method: :get, class:'dropdown-item' %>
						<%= button_to 'Settings', edit_account_registration_path, method: :get, class:'dropdown-item' %>
						<%= button_to 'Log Out', destroy_account_session_path, method: :delete, class:'dropdown-item' %>
					</ul>
					</div>
			<% else %>
				<div class='float-end'>
					<%= link_to 'Log In', new_account_session_path, class:'text-dark btn btn-danger' %>
					<%= link_to 'Sign Up', new_account_registration_path, class:'text-dark btn btn-danger' %>
				</div>
			<% end %>
			<p class='mt-4'><%= link_to 'Reddit Clone', root_path, class: 'navbar-brand text-light text-decoration-none' %></p>
			<div class='desktop-hide'>
				<%= render partial: 'public/headers' %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-dark'>
    <%= render partial: 'layouts/header' %>
    <% if notice %>
      <p class = "alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class = "alert alert-danger"><%= alert %></p>
    <% end %>
      <div class='container bg-dark'>
        <div>
          <div class='col-sm-12 pt-4'>
            <%= yield %>
          </div>
        </div>
      </div>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>